ALTER TABLE catalog_persons_categories DROP FOREIGN KEY FK_catalog_persons_categories_PortalId
ALTER TABLE content_publications_entries DROP FOREIGN KEY FK_content_publications_entries_CategoryId
ALTER TABLE content_publications_entries DROP FOREIGN KEY FK_content_publications_entries_PortalId
ALTER TABLE security_resources DROP FOREIGN KEY FK_security_resources_PortalId
ALTER TABLE security_resources DROP KEY UNQ_security_resources_0
ALTER TABLE security_actions DROP FOREIGN KEY FK_security_actions_PortalId
ALTER TABLE security_sessions DROP FOREIGN KEY FK_security_sessions_UserId
ALTER TABLE content_adverts_entries DROP FOREIGN KEY FK_content_adverts_entries_PortalId
ALTER TABLE content_adverts_entries DROP FOREIGN KEY FK_content_adverts_entries_CategoryId
ALTER TABLE catalog_banners_categories DROP FOREIGN KEY FK_catalog_banners_categories_PortalId
ALTER TABLE security_requests DROP FOREIGN KEY FK_security_requests_ActionId
ALTER TABLE catalog_objects_categories DROP FOREIGN KEY FK_catalog_objects_categories_PortalId
ALTER TABLE catalog_objects_entries DROP FOREIGN KEY FK_catalog_objects_entries_PortalId
ALTER TABLE catalog_objects_entries DROP FOREIGN KEY FK_catalog_objects_entries_CategoryId
ALTER TABLE catalog_persons_entries DROP FOREIGN KEY FK_catalog_persons_entries_CategoryId
ALTER TABLE catalog_persons_entries DROP FOREIGN KEY FK_catalog_persons_entries_PortalId
ALTER TABLE security_privileges DROP FOREIGN KEY FK_security_privileges_ResourceId
ALTER TABLE security_privileges DROP FOREIGN KEY FK_security_privileges_UserId
ALTER TABLE security_privileges DROP KEY UNQ_security_privileges_0
ALTER TABLE catalog_offers_categories DROP FOREIGN KEY FK_catalog_offers_categories_PortalId
ALTER TABLE content_publications_categories DROP FOREIGN KEY FK_content_publications_categories_PortalId
ALTER TABLE catalog_banners_entries DROP FOREIGN KEY FK_catalog_banners_entries_CategoryId
ALTER TABLE catalog_banners_entries DROP FOREIGN KEY FK_catalog_banners_entries_PortalId
ALTER TABLE content_adverts_categories DROP FOREIGN KEY FK_content_adverts_categories_PortalId
ALTER TABLE security_providers DROP FOREIGN KEY FK_security_providers_PortalId
ALTER TABLE security_providers DROP KEY UNQ_security_providers_0
ALTER TABLE security_users DROP FOREIGN KEY FK_security_users_PortalId
ALTER TABLE security_users DROP KEY UNQ_security_users_0
ALTER TABLE catalog_offers_entries DROP FOREIGN KEY FK_catalog_offers_entries_PortalId
ALTER TABLE catalog_offers_entries DROP FOREIGN KEY FK_catalog_offers_entries_ObjectId
ALTER TABLE catalog_offers_entries DROP FOREIGN KEY FK_catalog_offers_entries_CategoryId
DROP TABLE catalog_persons_categories
DROP TABLE content_publications_entries
DROP TABLE security_resources
DROP TABLE security_actions
DROP TABLE security_sessions
DROP TABLE content_adverts_entries
DROP TABLE catalog_banners_categories
DROP TABLE security_requests
DROP TABLE catalog_objects_categories
DROP TABLE catalog_objects_entries
DROP TABLE catalog_persons_entries
DROP TABLE security_portals
DROP TABLE security_privileges
DROP TABLE catalog_offers_categories
DROP TABLE content_publications_categories
DROP TABLE catalog_banners_entries
DROP TABLE content_adverts_categories
DROP TABLE security_providers
DROP TABLE security_users
DROP TABLE catalog_offers_entries
